"""add skill evidence

Revision ID: 0222bc62dba9
Revises: 11d0351c0e53
Create Date: 2026-09-11 22:48:46.077632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0222bc62dba9'
down_revision: Union[str, Sequence[str], None] = '11d0351c0e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_skill_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('evidence_reference', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['student_skill_id'], ['student_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_evidence_id'), 'skill_evidence', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_evidence_id'), table_name='skill_evidence')
    op.drop_table('skill_evidence')
    # ### end Alembic commands ###
