"""add opportunity skills

Revision ID: 1aba60d3ae37
Revises: d685619dfac9
Create Date: 2026-09-12 13:04:37.810195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aba60d3ae37'
down_revision: Union[str, Sequence[str], None] = 'd685619dfac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('importance', sa.String(length=30), nullable=False),
    sa.Column('minimum_proficiency', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_skills_id'), 'opportunity_skills', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_skills_id'), table_name='opportunity_skills')
    op.drop_table('opportunity_skills')
    # ### end Alembic commands ###
