"""add knowledge ingestion tracking

Revision ID: 6e0af0494f40
Revises: d428cf4914a3
Create Date: 2026-09-16 18:11:54.982394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e0af0494f40'
down_revision: Union[str, Sequence[str], None] = 'd428cf4914a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_ingestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stored_file_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stored_file_id'], ['stored_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_ingestions_id'), 'knowledge_ingestions', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_ingestions_status'), 'knowledge_ingestions', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_ingestions_stored_file_id'), 'knowledge_ingestions', ['stored_file_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_ingestions_stored_file_id'), table_name='knowledge_ingestions')
    op.drop_index(op.f('ix_knowledge_ingestions_status'), table_name='knowledge_ingestions')
    op.drop_index(op.f('ix_knowledge_ingestions_id'), table_name='knowledge_ingestions')
    op.drop_table('knowledge_ingestions')
    # ### end Alembic commands ###
