"""add project outcomes

Revision ID: 97a1e890f5c9
Revises: e2e281e2c27f
Create Date: 2026-09-12 12:01:24.415524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a1e890f5c9'
down_revision: Union[str, Sequence[str], None] = 'e2e281e2c27f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('outcome_type', sa.String(length=50), nullable=False),
    sa.Column('result', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_outcomes_id'), 'project_outcomes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_outcomes_id'), table_name='project_outcomes')
    op.drop_table('project_outcomes')
    # ### end Alembic commands ###
