"""add academic records

Revision ID: a86a6ab0fabc
Revises: 8f3a2c91d7b4
Create Date: 2026-09-11 22:12:04.253508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a86a6ab0fabc'
down_revision: Union[str, Sequence[str], None] = '8f3a2c91d7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('marks', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('grade_point', sa.Float(), nullable=True),
    sa.Column('attendance_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_records_id'), 'academic_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academic_records_id'), table_name='academic_records')
    op.drop_table('academic_records')
    # ### end Alembic commands ###
